### ISSUE TITLE
Failed to get DSID

### ISSUE THREAD

**Issue by rubberbird** [samm-git/jvpn#28]
getting the below error.

Enter PIN+password: *********
Transfer went ok
Got DSID
Unable to get DSID, exiting

Any way to debug this?

**Comment by AdnanHodzic** [comment]
I have this same problem, except I get DSID which seems to be empty. 

i.e:
<code>
Transfer went ok
Got DSID=, dfirst=1441369008, dlast=1441369008
</code>
<code>Unable to get DSID, exiting 
</code>

I tried changing upgrading/downgrading Java but without success. I tried switching between: OpenJDK  32/64 bit 7/8 and Oracle Java 7, same results.

Please note that with <i>all</i>  of these versions, accessing VPN via web interface works fine. 

Any other ideas?

**Comment by AurelienLourot** [comment]
I was having the same issue, which is fixed in [this fork](https://github.com/jpazdyga/jvpn).

**Comment by AdnanHodzic** [comment]
I found a way to configure Juniper VPN using openconnect tool, if you're interested please refer to my blog post: [Juniper/Pulse Secure VPN on Linux (2015 edition)](http://foolcontrol.org/?p=1737)
